language: node_js
env:
  global:
    - DATABASE_URL="postgresql://postgres:postgres@localhost:5432/testdb"
matrix:
  include:
    - node_js: "12"
cache:
  directories: [node_modules]
install: npm install
before_script:
  - psql -c 'create database testdb;' -U postgres
script:
  - npm run test
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
before_install:
  - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
